Repository gisaia/ARLAS-wui, pull requests merged in 2018-06, with the labels that each got.

#63 Fix share in config.json
  src/config.json
Labels: type:maintenance

#67 Feature/timeline
  package-lock.json
  package.json
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/styles.css
  src/styles/histogram.analytics.css
  src/styles/powerbars.css
  src/styles/swimlane.css
  src/styles/timeline.css
  yarn.lock
Labels: type:enhancement

#70 Fix configuration for map and timeline
  src/config.json
Labels: type:bug

#71 Feature/improve layer switcher
  src/app/app.component.html
  src/app/app.component.ts
  src/config.json
Labels: type:enhancement

#72 Remove scroll bar display on load
  src/app/app.component.css
Labels: type:bug

#73 Update stack dependencies
  package-lock.json
  yarn.lock
Labels: type:maintenance

#74 Display search value on init
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
Labels: type:bug
