Repository gisaia/ARLAS-wui, pull requests merged in 2018-09, with the labels that each got.

#89 Fix/dataset dialog validation
  src/app/components/dataset/dataset-add-dialog.component.html
  src/app/components/dataset/dataset.component.css
  src/app/components/dataset/dataset.component.html
  src/app/components/dataset/dataset.component.ts
Labels: type:bug

#92 Add toggle button for search & analytics
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/app/components/about/about.component.ts
  src/app/components/dataset/dataset-add-dialog.component.css
  src/app/components/dataset/dataset-dialog.component.css
  src/app/components/dataset/dataset.component.css
  src/app/components/dataset/dataset.component.html
  src/app/components/dataset/dataset.component.spec.ts
  src/app/components/dataset/dataset.component.ts
  src/app/components/filters-chips/filters-chips.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
  src/app/services/contributors.service.ts
Labels: type:enhancement

#94 Upgarde arlas-wui to 7.4.0
  package-lock.json
  package.json
  src/app/app.component.html
  src/config.json
  src/config.map.json
  yarn.lock
Labels: type:maintenance

#97 Add env variable for 'en' and 'fr' language file in start script
  scripts/start.sh
Labels: type:enhancement

#99 Add action 'zoom to' on each item in result list
  src/app/app.component.html
  src/app/app.component.ts
Labels: type:enhancement

#100 Prepare release of 7.4.1
  package-lock.json
  package.json
  yarn.lock
Labels: type:maintenance
